# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

<<<<<<< HEAD
- script: |
    npm install
=======
- script: 
    rm -rf node_modules
    rm -rf package-lock.json
    npm install react-scripts
    npm install react-scripts
>>>>>>> parent of 30ddd5f (Update azure-pipelines.yml for Azure Pipelines)
    npm run build
  displayName: 'npm install and build'
